### ISSUE TITLE
The app seems very old, but I trust that it's still "fit for purpose"?

### ISSUE THREAD

**Issue by danielkrajnik** [guardianproject/Ripple#28]
I came here from Aegis - authenticator app has a setting to be locked on a trigger like "Ripple". I'm surprised to see so little activity in this repo. Is the project "finished"? I'd like to trust it, it would be reassuring to know if it hasn't succumbed to "bit rot" yet.

**Comment by n8fr8** [comment]
Much of the value of it is based on the interaction with the third-party apps it supports. Ripple on its own is just a trigger. Please test with any app that you plan to use it with first.

Otherwise, we have been putting our physical safety attention into apps like Circulo: https://encirculo.org/en/

**Comment by eighthave** [comment]
Its a very simple app, so it needs little updating.  That said, we are just completing a update to fix some bugs on newer Android versions: v0.3.0
